/* Engine.JS is command-line only and is licensed under MIT. William Kenzie is the origional developer of this software. */
const scrapeYt = require("scrape-yt");
var searchTerm = process.argv.slice(2);
scrapeYt.search(`${searchTerm} "Auto-generated by YouTube."`, {
    type: "video"
}).then(videos => {
    var songs = []
    var Output = new Object
    for (i = 0; i < videos.length; i++) {
    if (!songs.includes(videos[i].title + " - " + videos[i].channel.name.replace(' - Topic','').replace('Official',''))) {
    songs.push(videos[i].title + " - " + videos[i].channel.name.replace(' - Topic','').replace('Official',''))
    if (Output.length > 0) {
    Output[Output.length + 1].name = videos[i].title
    Output[Output.length + 1].author = videos[i].channel.name.replace(' - Topic','').replace('Official','')
    Output[Output.length + 1].url = "https://youtube.com/watch?v=" + videos[i].id
    }
} else {
    Output[0].name = videos[i].title
    Output[0].author = videos[i].channel.name.replace(' - Topic','').replace('Official','')
    Output[0].url = "https://youtube.com/watch?v=" + videos[i].id
}
    }
    console.log(Output)
});